# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0002_auto_20160708_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
